import sqlalchemy as sa
import sqlalchemy.orm as so
from app import db
from app import db
from typing import Optional

class Character(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=False)
    slug: so.Mapped[Optional[str]] = so.mapped_column(sa.String(64), unique=True, nullable=True)
    game: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=False)

    def __repr__(self):
        return f"Character('{self.id}', '{self.name}','{self.game}')"
    
class HSRGame8(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=False)
    slug: so.Mapped[Optional[str]] = so.mapped_column(sa.String(64), unique=True, nullable=True)
    lightcone0: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone1: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone2: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone3: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    relic0: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    relic1: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    relic2: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament0: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament1: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament2: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    bodystat: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    feetstat: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    spherestat: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    ropestat: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    substats: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)

class HSRGame8multi(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=False)
    slug: so.Mapped[Optional[str]] = so.mapped_column(sa.String(64), unique=True, nullable=True)
    build1name: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone0a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone1a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone2a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone3a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    relic0a: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    relic1a: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    relic2a: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament0a: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament1a: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament2a: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    bodystata: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    feetstata: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    spherestata: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ropestata: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    substatsa: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    build2name: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone0b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone1b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone2b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    lightcone3b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    relic0b: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    relic1b: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    relic2b: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament0b: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament1b: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    ornament2b: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    bodystatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    feetstatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    spherestatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    ropestatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    substatsb: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=True)
    

class GenshinGame8(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=False)
    slug: so.Mapped[Optional[str]] = so.mapped_column(sa.String(64), unique=True, nullable=True)
    weapon0: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon1: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon2: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon3: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact0: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact1: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact2: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact3: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sandsstat: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    gobletstat: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    circletstat: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    substats: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)


class Genshin8Multi(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=False)
    slug: so.Mapped[Optional[str]] = so.mapped_column(sa.String(64), unique=True, nullable=True)
    build1name: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon0a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon1a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon2a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon3a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact0a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact1a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact2a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact3a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sandsstata: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    gobletstata: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    circletstata: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    substatsa: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    build2name: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon0b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon1b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon2b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon3b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact0b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact1b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact2b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact3b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sandsstatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    gobletstatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    circletstatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    substatsb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)

class Genshin8Multix3(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=False)
    slug: so.Mapped[Optional[str]] = so.mapped_column(sa.String(64), unique=True, nullable=True)
    build1name: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon0a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon1a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon2a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon3a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact0a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact1a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact2a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact3a: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sandsstata: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    gobletstata: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    circletstata: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    substatsa: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    build2name: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon0b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon1b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon2b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon3b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact0b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact1b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact2b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact3b: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sandsstatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    gobletstatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    circletstatb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    substatsb: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    build3name: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon0c: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon1c: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon2c: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon3c: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact0c: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact1c: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact2c: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    artifact3c: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sandsstatc: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    gobletstatc: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    circletstatc: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    substatsc: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)


class WuwaGame8(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=False)
    slug: so.Mapped[Optional[str]] = so.mapped_column(sa.String(64), unique=True, nullable=True)
    weapon0: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon1: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon2: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    weapon3: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    echo0: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    echo1: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    echo2: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sonata0: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sonata1: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    sonata2: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    echocost: so.Mapped[str] = so.mapped_column(sa.String(32), nullable=True)
    mainstat4: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=True)
    mainstat3: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=True)
    mainstat1: so.Mapped[str] = so.mapped_column(sa.String(64), nullable=True)
    substats: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    skillpriority: so.Mapped[str] = so.mapped_column(sa.String(128), nullable=True)
    
