"""Added third relic line

Revision ID: 0468cf617314
Revises: edbaff67145e
Create Date: 2025-07-25 20:30:16.495210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0468cf617314'
down_revision = 'edbaff67145e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hsr_game8', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relic2', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hsr_game8', schema=None) as batch_op:
        batch_op.drop_column('relic2')

    # ### end Alembic commands ###
