"""added Genshin game8 table

Revision ID: 09d3982b913b
Revises: 0468cf617314
Create Date: 2025-07-30 04:02:51.059994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d3982b913b'
down_revision = '0468cf617314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genshin_game8',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('weapon0', sa.String(length=128), nullable=True),
    sa.Column('weapon1', sa.String(length=128), nullable=True),
    sa.Column('weapon2', sa.String(length=128), nullable=True),
    sa.Column('weapon3', sa.String(length=128), nullable=True),
    sa.Column('artifact0', sa.String(length=128), nullable=True),
    sa.Column('artifact1', sa.String(length=128), nullable=True),
    sa.Column('artifact2', sa.String(length=128), nullable=True),
    sa.Column('artifact3', sa.String(length=128), nullable=True),
    sa.Column('sandsstat', sa.String(length=128), nullable=True),
    sa.Column('gobletstat', sa.String(length=128), nullable=True),
    sa.Column('circletstat', sa.String(length=128), nullable=True),
    sa.Column('substats', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genshin_game8')
    # ### end Alembic commands ###
