"""Add nullable slug column

Revision ID: 1d84fdf275a3
Revises: 6c418553cb23
Create Date: 2025-07-22 01:43:06.168193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d84fdf275a3'
down_revision = '6c418553cb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_character_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
