"""Allows nullable fields for Game8 table

Revision ID: 230afb367a77
Revises: ab19f33b2dbe
Create Date: 2025-07-25 18:58:35.395536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230afb367a77'
down_revision = 'ab19f33b2dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hsr_game8', schema=None) as batch_op:
        batch_op.alter_column('lightcone0',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('lightcone1',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('lightcone2',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('lightcone3',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('relic0',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('relic1',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('ornament0',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('ornament1',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('ornament2',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('bodystat',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('feetstat',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('spherestat',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('ropestat',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('substats',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hsr_game8', schema=None) as batch_op:
        batch_op.alter_column('substats',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('ropestat',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('spherestat',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('feetstat',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('bodystat',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('ornament2',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('ornament1',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('ornament0',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('relic1',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('relic0',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('lightcone3',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('lightcone2',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('lightcone1',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('lightcone0',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
