"""Added Wuwa Game8 table

Revision ID: 4f404f748cd2
Revises: 88eed5496b77
Create Date: 2025-08-01 22:06:24.686866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f404f748cd2'
down_revision = '88eed5496b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wuwa_game8',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('weapon0', sa.String(length=128), nullable=True),
    sa.Column('weapon1', sa.String(length=128), nullable=True),
    sa.Column('weapon2', sa.String(length=128), nullable=True),
    sa.Column('weapon3', sa.String(length=128), nullable=True),
    sa.Column('echo0', sa.String(length=128), nullable=True),
    sa.Column('echo1', sa.String(length=128), nullable=True),
    sa.Column('echo2', sa.String(length=128), nullable=True),
    sa.Column('sonata0', sa.String(length=128), nullable=True),
    sa.Column('sonata1', sa.String(length=128), nullable=True),
    sa.Column('sonata2', sa.String(length=128), nullable=True),
    sa.Column('mainstat4', sa.String(length=64), nullable=True),
    sa.Column('mainstat3', sa.String(length=64), nullable=True),
    sa.Column('mainstat1', sa.String(length=64), nullable=True),
    sa.Column('substats', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wuwa_game8')
    # ### end Alembic commands ###
