"""changed disc drive data

Revision ID: 5d6b42fae887
Revises: ab628edc35ae
Create Date: 2025-08-04 14:54:45.796613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6b42fae887'
down_revision = 'ab628edc35ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zzz_game8', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive4pcdisc0', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('drive2pcdisc0', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('drive4pcdisc1', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('drive2pcdisc1', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('drive4pcdisc2', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('drive2pcdisc2', sa.String(length=128), nullable=True))
        batch_op.drop_column('drivedisc1')
        batch_op.drop_column('drivedisc0')
        batch_op.drop_column('drivedisc2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zzz_game8', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drivedisc2', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('drivedisc0', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('drivedisc1', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('drive2pcdisc2')
        batch_op.drop_column('drive4pcdisc2')
        batch_op.drop_column('drive2pcdisc1')
        batch_op.drop_column('drive4pcdisc1')
        batch_op.drop_column('drive2pcdisc0')
        batch_op.drop_column('drive4pcdisc0')

    # ### end Alembic commands ###
