"""Added table for characters with 3 builds

Revision ID: 673196c8f4d9
Revises: 8e9f4a566c4d
Create Date: 2025-07-31 02:23:29.096936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673196c8f4d9'
down_revision = '8e9f4a566c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genshin8_multix3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('build1name', sa.String(length=128), nullable=True),
    sa.Column('weapon0a', sa.String(length=128), nullable=True),
    sa.Column('weapon1a', sa.String(length=128), nullable=True),
    sa.Column('weapon2a', sa.String(length=128), nullable=True),
    sa.Column('weapon3a', sa.String(length=128), nullable=True),
    sa.Column('artifact0a', sa.String(length=128), nullable=True),
    sa.Column('artifact1a', sa.String(length=128), nullable=True),
    sa.Column('artifact2a', sa.String(length=128), nullable=True),
    sa.Column('artifact3a', sa.String(length=128), nullable=True),
    sa.Column('sandsstata', sa.String(length=128), nullable=True),
    sa.Column('gobletstata', sa.String(length=128), nullable=True),
    sa.Column('circletstata', sa.String(length=128), nullable=True),
    sa.Column('substatsa', sa.String(length=128), nullable=True),
    sa.Column('build2name', sa.String(length=128), nullable=True),
    sa.Column('weapon0b', sa.String(length=128), nullable=True),
    sa.Column('weapon1b', sa.String(length=128), nullable=True),
    sa.Column('weapon2b', sa.String(length=128), nullable=True),
    sa.Column('weapon3b', sa.String(length=128), nullable=True),
    sa.Column('artifact0b', sa.String(length=128), nullable=True),
    sa.Column('artifact1b', sa.String(length=128), nullable=True),
    sa.Column('artifact2b', sa.String(length=128), nullable=True),
    sa.Column('artifact3b', sa.String(length=128), nullable=True),
    sa.Column('sandsstatb', sa.String(length=128), nullable=True),
    sa.Column('gobletstatb', sa.String(length=128), nullable=True),
    sa.Column('circletstatb', sa.String(length=128), nullable=True),
    sa.Column('substatsb', sa.String(length=128), nullable=True),
    sa.Column('build3name', sa.String(length=128), nullable=True),
    sa.Column('weapon0c', sa.String(length=128), nullable=True),
    sa.Column('weapon1c', sa.String(length=128), nullable=True),
    sa.Column('weapon2c', sa.String(length=128), nullable=True),
    sa.Column('weapon3c', sa.String(length=128), nullable=True),
    sa.Column('artifact0c', sa.String(length=128), nullable=True),
    sa.Column('artifact1c', sa.String(length=128), nullable=True),
    sa.Column('artifact2c', sa.String(length=128), nullable=True),
    sa.Column('artifact3c', sa.String(length=128), nullable=True),
    sa.Column('sandsstatc', sa.String(length=128), nullable=True),
    sa.Column('gobletstatc', sa.String(length=128), nullable=True),
    sa.Column('circletstatc', sa.String(length=128), nullable=True),
    sa.Column('substatsc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genshin8_multix3')
    # ### end Alembic commands ###
