"""Initial migration

Revision ID: 88eed5496b77
Revises: 
Create Date: 2025-07-31 21:28:15.915433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88eed5496b77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('game', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('genshin8_multi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('build1name', sa.String(length=128), nullable=True),
    sa.Column('weapon0a', sa.String(length=128), nullable=True),
    sa.Column('weapon1a', sa.String(length=128), nullable=True),
    sa.Column('weapon2a', sa.String(length=128), nullable=True),
    sa.Column('weapon3a', sa.String(length=128), nullable=True),
    sa.Column('artifact0a', sa.String(length=128), nullable=True),
    sa.Column('artifact1a', sa.String(length=128), nullable=True),
    sa.Column('artifact2a', sa.String(length=128), nullable=True),
    sa.Column('artifact3a', sa.String(length=128), nullable=True),
    sa.Column('sandsstata', sa.String(length=128), nullable=True),
    sa.Column('gobletstata', sa.String(length=128), nullable=True),
    sa.Column('circletstata', sa.String(length=128), nullable=True),
    sa.Column('substatsa', sa.String(length=128), nullable=True),
    sa.Column('build2name', sa.String(length=128), nullable=True),
    sa.Column('weapon0b', sa.String(length=128), nullable=True),
    sa.Column('weapon1b', sa.String(length=128), nullable=True),
    sa.Column('weapon2b', sa.String(length=128), nullable=True),
    sa.Column('weapon3b', sa.String(length=128), nullable=True),
    sa.Column('artifact0b', sa.String(length=128), nullable=True),
    sa.Column('artifact1b', sa.String(length=128), nullable=True),
    sa.Column('artifact2b', sa.String(length=128), nullable=True),
    sa.Column('artifact3b', sa.String(length=128), nullable=True),
    sa.Column('sandsstatb', sa.String(length=128), nullable=True),
    sa.Column('gobletstatb', sa.String(length=128), nullable=True),
    sa.Column('circletstatb', sa.String(length=128), nullable=True),
    sa.Column('substatsb', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('genshin8_multix3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('build1name', sa.String(length=128), nullable=True),
    sa.Column('weapon0a', sa.String(length=128), nullable=True),
    sa.Column('weapon1a', sa.String(length=128), nullable=True),
    sa.Column('weapon2a', sa.String(length=128), nullable=True),
    sa.Column('weapon3a', sa.String(length=128), nullable=True),
    sa.Column('artifact0a', sa.String(length=128), nullable=True),
    sa.Column('artifact1a', sa.String(length=128), nullable=True),
    sa.Column('artifact2a', sa.String(length=128), nullable=True),
    sa.Column('artifact3a', sa.String(length=128), nullable=True),
    sa.Column('sandsstata', sa.String(length=128), nullable=True),
    sa.Column('gobletstata', sa.String(length=128), nullable=True),
    sa.Column('circletstata', sa.String(length=128), nullable=True),
    sa.Column('substatsa', sa.String(length=128), nullable=True),
    sa.Column('build2name', sa.String(length=128), nullable=True),
    sa.Column('weapon0b', sa.String(length=128), nullable=True),
    sa.Column('weapon1b', sa.String(length=128), nullable=True),
    sa.Column('weapon2b', sa.String(length=128), nullable=True),
    sa.Column('weapon3b', sa.String(length=128), nullable=True),
    sa.Column('artifact0b', sa.String(length=128), nullable=True),
    sa.Column('artifact1b', sa.String(length=128), nullable=True),
    sa.Column('artifact2b', sa.String(length=128), nullable=True),
    sa.Column('artifact3b', sa.String(length=128), nullable=True),
    sa.Column('sandsstatb', sa.String(length=128), nullable=True),
    sa.Column('gobletstatb', sa.String(length=128), nullable=True),
    sa.Column('circletstatb', sa.String(length=128), nullable=True),
    sa.Column('substatsb', sa.String(length=128), nullable=True),
    sa.Column('build3name', sa.String(length=128), nullable=True),
    sa.Column('weapon0c', sa.String(length=128), nullable=True),
    sa.Column('weapon1c', sa.String(length=128), nullable=True),
    sa.Column('weapon2c', sa.String(length=128), nullable=True),
    sa.Column('weapon3c', sa.String(length=128), nullable=True),
    sa.Column('artifact0c', sa.String(length=128), nullable=True),
    sa.Column('artifact1c', sa.String(length=128), nullable=True),
    sa.Column('artifact2c', sa.String(length=128), nullable=True),
    sa.Column('artifact3c', sa.String(length=128), nullable=True),
    sa.Column('sandsstatc', sa.String(length=128), nullable=True),
    sa.Column('gobletstatc', sa.String(length=128), nullable=True),
    sa.Column('circletstatc', sa.String(length=128), nullable=True),
    sa.Column('substatsc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('genshin_game8',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('weapon0', sa.String(length=128), nullable=True),
    sa.Column('weapon1', sa.String(length=128), nullable=True),
    sa.Column('weapon2', sa.String(length=128), nullable=True),
    sa.Column('weapon3', sa.String(length=128), nullable=True),
    sa.Column('artifact0', sa.String(length=128), nullable=True),
    sa.Column('artifact1', sa.String(length=128), nullable=True),
    sa.Column('artifact2', sa.String(length=128), nullable=True),
    sa.Column('artifact3', sa.String(length=128), nullable=True),
    sa.Column('sandsstat', sa.String(length=128), nullable=True),
    sa.Column('gobletstat', sa.String(length=128), nullable=True),
    sa.Column('circletstat', sa.String(length=128), nullable=True),
    sa.Column('substats', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('hsr_game8',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('lightcone0', sa.String(length=128), nullable=True),
    sa.Column('lightcone1', sa.String(length=128), nullable=True),
    sa.Column('lightcone2', sa.String(length=128), nullable=True),
    sa.Column('lightcone3', sa.String(length=128), nullable=True),
    sa.Column('relic0', sa.String(length=256), nullable=True),
    sa.Column('relic1', sa.String(length=256), nullable=True),
    sa.Column('relic2', sa.String(length=256), nullable=True),
    sa.Column('ornament0', sa.String(length=256), nullable=True),
    sa.Column('ornament1', sa.String(length=256), nullable=True),
    sa.Column('ornament2', sa.String(length=256), nullable=True),
    sa.Column('bodystat', sa.String(length=256), nullable=True),
    sa.Column('feetstat', sa.String(length=128), nullable=True),
    sa.Column('spherestat', sa.String(length=128), nullable=True),
    sa.Column('ropestat', sa.String(length=128), nullable=True),
    sa.Column('substats', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('hsr_game8multi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('build1name', sa.String(length=128), nullable=True),
    sa.Column('lightcone0a', sa.String(length=128), nullable=True),
    sa.Column('lightcone1a', sa.String(length=128), nullable=True),
    sa.Column('lightcone2a', sa.String(length=128), nullable=True),
    sa.Column('lightcone3a', sa.String(length=128), nullable=True),
    sa.Column('relic0a', sa.String(length=256), nullable=True),
    sa.Column('relic1a', sa.String(length=256), nullable=True),
    sa.Column('relic2a', sa.String(length=256), nullable=True),
    sa.Column('ornament0a', sa.String(length=256), nullable=True),
    sa.Column('ornament1a', sa.String(length=256), nullable=True),
    sa.Column('ornament2a', sa.String(length=256), nullable=True),
    sa.Column('bodystata', sa.String(length=128), nullable=True),
    sa.Column('feetstata', sa.String(length=128), nullable=True),
    sa.Column('spherestata', sa.String(length=256), nullable=True),
    sa.Column('ropestata', sa.String(length=256), nullable=True),
    sa.Column('substatsa', sa.String(length=256), nullable=True),
    sa.Column('build2name', sa.String(length=128), nullable=True),
    sa.Column('lightcone0b', sa.String(length=128), nullable=True),
    sa.Column('lightcone1b', sa.String(length=128), nullable=True),
    sa.Column('lightcone2b', sa.String(length=128), nullable=True),
    sa.Column('lightcone3b', sa.String(length=128), nullable=True),
    sa.Column('relic0b', sa.String(length=256), nullable=True),
    sa.Column('relic1b', sa.String(length=256), nullable=True),
    sa.Column('relic2b', sa.String(length=256), nullable=True),
    sa.Column('ornament0b', sa.String(length=256), nullable=True),
    sa.Column('ornament1b', sa.String(length=256), nullable=True),
    sa.Column('ornament2b', sa.String(length=256), nullable=True),
    sa.Column('bodystatb', sa.String(length=128), nullable=True),
    sa.Column('feetstatb', sa.String(length=128), nullable=True),
    sa.Column('spherestatb', sa.String(length=128), nullable=True),
    sa.Column('ropestatb', sa.String(length=128), nullable=True),
    sa.Column('substatsb', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hsr_game8multi')
    op.drop_table('hsr_game8')
    op.drop_table('genshin_game8')
    op.drop_table('genshin8_multix3')
    op.drop_table('genshin8_multi')
    op.drop_table('character')
    # ### end Alembic commands ###
