"""AddedHSR multi build table

Revision ID: 8a76cc29b7db
Revises: 673196c8f4d9
Create Date: 2025-07-31 11:46:57.392957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a76cc29b7db'
down_revision = '673196c8f4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsr_game8multi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('build1name', sa.String(length=128), nullable=True),
    sa.Column('lightcone0a', sa.String(length=128), nullable=True),
    sa.Column('lightcone1a', sa.String(length=128), nullable=True),
    sa.Column('lightcone2a', sa.String(length=128), nullable=True),
    sa.Column('lightcone3a', sa.String(length=128), nullable=True),
    sa.Column('relic0a', sa.String(length=128), nullable=True),
    sa.Column('relic1a', sa.String(length=128), nullable=True),
    sa.Column('relic2a', sa.String(length=128), nullable=True),
    sa.Column('ornament0a', sa.String(length=128), nullable=True),
    sa.Column('ornament1a', sa.String(length=128), nullable=True),
    sa.Column('ornament2a', sa.String(length=128), nullable=True),
    sa.Column('bodystata', sa.String(length=128), nullable=True),
    sa.Column('feetstata', sa.String(length=128), nullable=True),
    sa.Column('spherestata', sa.String(length=128), nullable=True),
    sa.Column('ropestata', sa.String(length=128), nullable=True),
    sa.Column('substatsa', sa.String(length=128), nullable=True),
    sa.Column('build2name', sa.String(length=128), nullable=True),
    sa.Column('lightcone0b', sa.String(length=128), nullable=True),
    sa.Column('lightcone1b', sa.String(length=128), nullable=True),
    sa.Column('lightcone2b', sa.String(length=128), nullable=True),
    sa.Column('lightcone3b', sa.String(length=128), nullable=True),
    sa.Column('relic0b', sa.String(length=128), nullable=True),
    sa.Column('relic1b', sa.String(length=128), nullable=True),
    sa.Column('relic2b', sa.String(length=128), nullable=True),
    sa.Column('ornament0b', sa.String(length=128), nullable=True),
    sa.Column('ornament1b', sa.String(length=128), nullable=True),
    sa.Column('ornament2b', sa.String(length=128), nullable=True),
    sa.Column('bodystatb', sa.String(length=128), nullable=True),
    sa.Column('feetstatb', sa.String(length=128), nullable=True),
    sa.Column('spherestatb', sa.String(length=128), nullable=True),
    sa.Column('ropestatb', sa.String(length=128), nullable=True),
    sa.Column('substatsb', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hsr_game8multi')
    # ### end Alembic commands ###
