"""Renamed fields for clarity

Revision ID: 8e9f4a566c4d
Revises: fec28b906dc0
Create Date: 2025-07-31 02:10:04.910782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9f4a566c4d'
down_revision = 'fec28b906dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genshin8_multi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weapon0a', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon1a', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon2a', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon3a', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact0a', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact1a', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact2a', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact3a', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('sandsstata', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('gobletstata', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('circletstata', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('substatsa', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon0b', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon1b', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon2b', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon3b', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact0b', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact1b', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact2b', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact3b', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('sandsstatb', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('gobletstatb', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('circletstatb', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('substatsb', sa.String(length=128), nullable=True))
        batch_op.drop_column('sandsstat')
        batch_op.drop_column('substats')
        batch_op.drop_column('weapon3')
        batch_op.drop_column('circletstat')
        batch_op.drop_column('weapon0')
        batch_op.drop_column('artifact0')
        batch_op.drop_column('artifact1')
        batch_op.drop_column('artifact2')
        batch_op.drop_column('weapon1')
        batch_op.drop_column('gobletstat')
        batch_op.drop_column('weapon2')
        batch_op.drop_column('artifact3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genshin8_multi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artifact3', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon2', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('gobletstat', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon1', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact2', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact1', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('artifact0', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon0', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('circletstat', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('weapon3', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('substats', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('sandsstat', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('substatsb')
        batch_op.drop_column('circletstatb')
        batch_op.drop_column('gobletstatb')
        batch_op.drop_column('sandsstatb')
        batch_op.drop_column('artifact3b')
        batch_op.drop_column('artifact2b')
        batch_op.drop_column('artifact1b')
        batch_op.drop_column('artifact0b')
        batch_op.drop_column('weapon3b')
        batch_op.drop_column('weapon2b')
        batch_op.drop_column('weapon1b')
        batch_op.drop_column('weapon0b')
        batch_op.drop_column('substatsa')
        batch_op.drop_column('circletstata')
        batch_op.drop_column('gobletstata')
        batch_op.drop_column('sandsstata')
        batch_op.drop_column('artifact3a')
        batch_op.drop_column('artifact2a')
        batch_op.drop_column('artifact1a')
        batch_op.drop_column('artifact0a')
        batch_op.drop_column('weapon3a')
        batch_op.drop_column('weapon2a')
        batch_op.drop_column('weapon1a')
        batch_op.drop_column('weapon0a')

    # ### end Alembic commands ###
