"""added stat priority to Wuwa

Revision ID: a8095fd29221
Revises: 4f404f748cd2
Create Date: 2025-08-01 23:38:31.549172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8095fd29221'
down_revision = '4f404f748cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wuwa_game8', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skillpriority', sa.String(length=128), nullable=True))
        batch_op.alter_column('substats',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wuwa_game8', schema=None) as batch_op:
        batch_op.alter_column('substats',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('skillpriority')

    # ### end Alembic commands ###
