"""Adding Game8 table for HSR

Revision ID: ab19f33b2dbe
Revises: 1d84fdf275a3
Create Date: 2025-07-25 18:55:09.054307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab19f33b2dbe'
down_revision = '1d84fdf275a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsr_game8',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('lightcone0', sa.String(length=64), nullable=False),
    sa.Column('lightcone1', sa.String(length=64), nullable=False),
    sa.Column('lightcone2', sa.String(length=64), nullable=False),
    sa.Column('lightcone3', sa.String(length=64), nullable=False),
    sa.Column('relic0', sa.String(length=128), nullable=False),
    sa.Column('relic1', sa.String(length=128), nullable=False),
    sa.Column('ornament0', sa.String(length=128), nullable=False),
    sa.Column('ornament1', sa.String(length=128), nullable=False),
    sa.Column('ornament2', sa.String(length=128), nullable=False),
    sa.Column('bodystat', sa.String(length=128), nullable=False),
    sa.Column('feetstat', sa.String(length=128), nullable=False),
    sa.Column('spherestat', sa.String(length=128), nullable=False),
    sa.Column('ropestat', sa.String(length=128), nullable=False),
    sa.Column('substats', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hsr_game8')
    # ### end Alembic commands ###
