"""Added ZZZ Game8 table

Revision ID: ab628edc35ae
Revises: b92edf629490
Create Date: 2025-08-04 04:20:51.514052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab628edc35ae'
down_revision = 'b92edf629490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zzz_game8',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('wengine0', sa.String(length=128), nullable=True),
    sa.Column('wengine1', sa.String(length=128), nullable=True),
    sa.Column('wengine2', sa.String(length=128), nullable=True),
    sa.Column('wengine3', sa.String(length=128), nullable=True),
    sa.Column('drivedisc0', sa.String(length=128), nullable=True),
    sa.Column('drivedisc1', sa.String(length=128), nullable=True),
    sa.Column('drivedisc2', sa.String(length=128), nullable=True),
    sa.Column('discstat6', sa.String(length=128), nullable=True),
    sa.Column('discstat5', sa.String(length=128), nullable=True),
    sa.Column('discstat4', sa.String(length=128), nullable=True),
    sa.Column('discsubstat', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zzz_game8')
    # ### end Alembic commands ###
