"""added  echo cost

Revision ID: b92edf629490
Revises: a8095fd29221
Create Date: 2025-08-02 05:53:08.538458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92edf629490'
down_revision = 'a8095fd29221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wuwa_game8', schema=None) as batch_op:
        batch_op.add_column(sa.Column('echocost', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wuwa_game8', schema=None) as batch_op:
        batch_op.drop_column('echocost')

    # ### end Alembic commands ###
