"""removed unneeded cols

Revision ID: ee9f5805abf9
Revises: 5d6b42fae887
Create Date: 2025-08-04 15:29:05.758616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9f5805abf9'
down_revision = '5d6b42fae887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zzz_game8', schema=None) as batch_op:
        batch_op.drop_column('drive2pcdisc2')
        batch_op.drop_column('drive4pcdisc2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zzz_game8', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive4pcdisc2', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('drive2pcdisc2', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
