"""added wuwa game8 multi table

Revision ID: fbae7d2fe8b7
Revises: ee9f5805abf9
Create Date: 2025-08-05 03:18:57.514194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbae7d2fe8b7'
down_revision = 'ee9f5805abf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wuwa_game8_multi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('build1name', sa.String(length=128), nullable=True),
    sa.Column('weapon0a', sa.String(length=128), nullable=True),
    sa.Column('weapon1a', sa.String(length=128), nullable=True),
    sa.Column('weapon2a', sa.String(length=128), nullable=True),
    sa.Column('weapon3a', sa.String(length=128), nullable=True),
    sa.Column('echo0a', sa.String(length=128), nullable=True),
    sa.Column('echo1a', sa.String(length=128), nullable=True),
    sa.Column('echo2a', sa.String(length=128), nullable=True),
    sa.Column('sonata0a', sa.String(length=128), nullable=True),
    sa.Column('sonata1a', sa.String(length=128), nullable=True),
    sa.Column('sonata2a', sa.String(length=128), nullable=True),
    sa.Column('echocosta', sa.String(length=32), nullable=True),
    sa.Column('mainstat4a', sa.String(length=64), nullable=True),
    sa.Column('mainstat3a', sa.String(length=64), nullable=True),
    sa.Column('mainstat1a', sa.String(length=64), nullable=True),
    sa.Column('substatsa', sa.String(length=128), nullable=True),
    sa.Column('skillprioritya', sa.String(length=128), nullable=True),
    sa.Column('build2name', sa.String(length=128), nullable=True),
    sa.Column('weapon0b', sa.String(length=128), nullable=True),
    sa.Column('weapon1b', sa.String(length=128), nullable=True),
    sa.Column('weapon2b', sa.String(length=128), nullable=True),
    sa.Column('weapon3b', sa.String(length=128), nullable=True),
    sa.Column('echo0b', sa.String(length=128), nullable=True),
    sa.Column('echo1b', sa.String(length=128), nullable=True),
    sa.Column('echo2b', sa.String(length=128), nullable=True),
    sa.Column('sonata0b', sa.String(length=128), nullable=True),
    sa.Column('sonata1b', sa.String(length=128), nullable=True),
    sa.Column('sonata2b', sa.String(length=128), nullable=True),
    sa.Column('echocostb', sa.String(length=32), nullable=True),
    sa.Column('mainstat4b', sa.String(length=64), nullable=True),
    sa.Column('mainstat3b', sa.String(length=64), nullable=True),
    sa.Column('mainstat1b', sa.String(length=64), nullable=True),
    sa.Column('substatsb', sa.String(length=128), nullable=True),
    sa.Column('skillpriorityb', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wuwa_game8_multi')
    # ### end Alembic commands ###
