"""Added Genshin multi builds

Revision ID: fec28b906dc0
Revises: 09d3982b913b
Create Date: 2025-07-31 02:08:40.491366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec28b906dc0'
down_revision = '09d3982b913b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genshin8_multi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('build1name', sa.String(length=128), nullable=True),
    sa.Column('weapon0', sa.String(length=128), nullable=True),
    sa.Column('weapon1', sa.String(length=128), nullable=True),
    sa.Column('weapon2', sa.String(length=128), nullable=True),
    sa.Column('weapon3', sa.String(length=128), nullable=True),
    sa.Column('artifact0', sa.String(length=128), nullable=True),
    sa.Column('artifact1', sa.String(length=128), nullable=True),
    sa.Column('artifact2', sa.String(length=128), nullable=True),
    sa.Column('artifact3', sa.String(length=128), nullable=True),
    sa.Column('sandsstat', sa.String(length=128), nullable=True),
    sa.Column('gobletstat', sa.String(length=128), nullable=True),
    sa.Column('circletstat', sa.String(length=128), nullable=True),
    sa.Column('substats', sa.String(length=128), nullable=True),
    sa.Column('build2name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genshin8_multi')
    # ### end Alembic commands ###
